const express = require('express');
const passport = require('passport');
const router = express.Router();
import PostController from '../controller/PostController';
import Auth from '../middleware/auth';
const multer = require('multer');
const upload = multer({ dest: 'uploads/' });
router.post('/upload', upload.any(), Auth.origin, PostController.upload);
router.post('/remove', Auth.origin, PostController.removePost);
module.exports = router;
